[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/about"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/details"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/faq"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/room-allotment"
  to = "/index.html"
  status = 200

[headers]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate" 